IncomingMessage {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList {
      head: null,
      tail: null,
      length: 0
    },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    defaultEncoding: 'utf8',
    ranOut: false,
    awaitDrain: 0,
    readingMore: true,
    decoder: null,
    encoding: null
  },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  socket: Socket {
    connecting: false,
    _hadError: false,
    _handle: TCP {
      bytesRead: 415,
      _externalStream: {},
      fd: -1,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events: {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function],
      error: [Function: socketOnError],
      close: [Object],
      data: [Function: socketOnData],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 0,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _idleTimeout: 120000,
    _idleNext: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idlePrev: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 10255,
    parser: HTTPParser {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage: ServerResponse {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: false,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      socket: [Circular],
      connection: [Circular],
      _header: null,
      _headers: [Object],
      _headerNames: [Object],
      _onPendingData: [Function: updateOutgoingData],
      req: [Circular],
      locals: {}
    }
  },
  connection: Socket {
    connecting: false,
    _hadError: false,
    _handle: TCP {
      bytesRead: 415,
      _externalStream: {},
      fd: -1,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events: {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function],
      error: [Function: socketOnError],
      close: [Object],
      data: [Function: socketOnData],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 0,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _idleTimeout: 120000,
    _idleNext: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idlePrev: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 10255,
    parser: HTTPParser {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage: ServerResponse {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: false,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      socket: [Circular],
      connection: [Circular],
      _header: null,
      _headers: [Object],
      _headerNames: [Object],
      _onPendingData: [Function: updateOutgoingData],
      req: [Circular],
      locals: {}
    }
  },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: false,
  headers: {
    host: '192.168.1.101:8090',
    connection: 'keep-alive',
    'cache-control': 'max-age=0',
    'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTM
    L,
    like Gecko) Chrome / 62.0 .3202 .89 Safari / 537.36 ',
  'upgrade-insecure-requests': '1',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,i
  mage / apng,
  *
  /*;q=0.8',
       'accept-encoding': 'gzip, deflate',
       'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8' },
    rawHeaders:
     [ 'Host',
       '192.168.1.101:8090',
       'Connection',
       'keep-alive',
       'Cache-Control',
       'max-age=0',
       'User-Agent',
       'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
   Chrome/62.0.3202.89 Safari/537.36',
       'Upgrade-Insecure-Requests',
       '1',
       'Accept',
       'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apn
  g,*/
  * ;q = 0.8 ',
  'Accept-Encoding',
  'gzip, deflate',
  'Accept-Language',
  'zh-CN,zh;q=0.9,en;q=0.8'],
trailers: {},
  rawTrailers: [],
  upgrade: false,
  url: '/',
  method: 'GET',
  statusCode: null,
  statusMessage: null,
  client:
  Socket {
    connecting: false,
    _hadError: false,
    _handle: TCP {
      bytesRead: 415,
      _externalStream: {},
      fd: -1,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events: {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function],
      error: [Function: socketOnError],
      close: [Object],
      data: [Function: socketOnData],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 0,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _server: Server {
      domain: null,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      _connectionKey: '6::::8090'
    },
    _idleTimeout: 120000,
    _idleNext: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idlePrev: TimersList {
      _idleNext: [Circular],
      _idlePrev: [Circular],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 10255,
    parser: HTTPParser {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage: ServerResponse {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: false,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: false,
      socket: [Circular],
      connection: [Circular],
      _header: null,
      _headers: [Object],
      _headerNames: [Object],
      _onPendingData: [Function: updateOutgoingData],
      req: [Circular],
      locals: {}
    }
  },
  _consuming: false,
  _dumped: false,
  next: [Function: next],
  baseUrl: '',
  originalUrl: '/',
  _parsedUrl:
  Url {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: null,
    query: null,
    pathname: '/',
    path: '/',
    href: '/',
    _raw: '/'
  },
  params: {},
  query: {},
  res:
  ServerResponse {
    domain: null,
    _events: {
      finish: [Function: resOnFinish]
    },
    _eventsCount: 1,
    _maxListeners: undefined,
    output: [],
    outputEncodings: [],
    outputCallbacks: [],
    outputSize: 0,
    writable: true,
    _last: false,
    upgrading: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedHeader: {},
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: false,
    _headerSent: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 0,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Object],
      _idleStart: 10255,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Circular]
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 0,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Object],
      _idleStart: 10255,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Circular]
    },
    _header: null,
    _headers: {
      'x-powered-by': 'Express'
    },
    _headerNames: {
      'x-powered-by': 'X-Powered-By'
    },
    _onPendingData: [Function: updateOutgoingData],
    req: [Circular],
    locals: {}
  }
}